version: '3'
services:
  cache:
    image: redis:latest
    command: [ "redis-server", "--protected-mode", "no" ]
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
  vehicle-api:
    build: .
    container_name: vehicle_api
    image: lucasciannela/vehicle-api
    restart: always
    links:
      - cache
    ports:
      - 8080:8080
    environment:
      - SPRING_ENVIRONMENT=prod
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_S3_BUCKET_NAME
      - AWS_ENDPOINT