spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cache:
    type: redis
---
aws:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      region: ${AWS_REGION}
      bucketName: ${AWS_S3_BUCKET_NAME}
      endpoint: ${AWS_ENDPOINT}
